import "server-only";
import path from "path";
import { Document, Page, Text, View, StyleSheet, Font } from "@react-pdf/renderer";
import { format } from "date-fns";
import { toSchoolZone } from "@/lib/school-time";

// A script font for the signature lines only — registered from a locally
// installed package (node_modules), never fetched over the network at
// render time, so PDF generation never depends on an external font host
// being reachable. The rest of the document uses react-pdf's built-in
// Helvetica, which needs no font file at all.
Font.register({
  family: "DancingScript",
  src: path.join(process.cwd(), "node_modules/@fontsource/dancing-script/files/dancing-script-latin-400-normal.woff"),
});

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 11, fontFamily: "Helvetica", color: "#111827" },
  title: { fontSize: 18, fontWeight: 700, marginBottom: 4 },
  subtitle: { fontSize: 11, color: "#6b7280", marginBottom: 20 },
  sectionLabel: { fontSize: 9, textTransform: "uppercase", color: "#6b7280", marginBottom: 2, marginTop: 14 },
  value: { fontSize: 11, lineHeight: 1.4 },
  statusBadge: { fontSize: 10, marginBottom: 16, color: "#374151" },
  signatureBlock: { marginTop: 28, borderTop: "1 solid #d1d5db", paddingTop: 14 },
  signatureRow: { flexDirection: "row", justifyContent: "space-between", marginBottom: 18 },
  signatureCol: { width: "48%" },
  signatureRole: { fontSize: 9, textTransform: "uppercase", color: "#6b7280", marginBottom: 4 },
  signatureName: { fontFamily: "DancingScript", fontSize: 22, color: "#111827" },
  signaturePlaceholder: { fontSize: 10, color: "#9ca3af", fontStyle: "italic" },
  signatureMeta: { fontSize: 8, color: "#6b7280", marginTop: 2 },
  footer: { position: "absolute", bottom: 30, left: 40, right: 40, fontSize: 8, color: "#9ca3af", textAlign: "center" },
});

export type ClubRegistrationPdfData = {
  clubName: string;
  schoolYear: string;
  description: string;
  meetingSchedule: string | null;
  meetingLocation: string | null;
  fundraisingGuidelines: string | null;
  status: string;
  sponsorName: string | null;
  sponsorSignedAt: Date | null;
  adminName: string | null;
  adminSignedAt: Date | null;
  generatedAt: Date;
};

function SignatureLine({ role, name, signedAt }: { role: string; name: string | null; signedAt: Date | null }) {
  return (
    <View style={styles.signatureCol}>
      <Text style={styles.signatureRole}>{role}</Text>
      {name ? (
        <>
          <Text style={styles.signatureName}>{name}</Text>
          <Text style={styles.signatureMeta}>Signed {signedAt ? format(toSchoolZone(signedAt), "MMMM d, yyyy 'at' h:mm a") : ""} — tied to their authenticated ClubSync account</Text>
        </>
      ) : (
        <Text style={styles.signaturePlaceholder}>Not yet signed</Text>
      )}
    </View>
  );
}

export function ClubRegistrationPdf(data: ClubRegistrationPdfData) {
  return (
    <Document title={`${data.clubName} — ${data.schoolYear} Registration`}>
      <Page size="LETTER" style={styles.page}>
        <Text style={styles.title}>Club Registration</Text>
        <Text style={styles.subtitle}>{data.clubName} — {data.schoolYear}</Text>
        <Text style={styles.statusBadge}>Status: {data.status.replace(/_/g, " ")}</Text>

        <Text style={styles.sectionLabel}>Description</Text>
        <Text style={styles.value}>{data.description}</Text>

        {data.meetingSchedule && (
          <>
            <Text style={styles.sectionLabel}>Meeting Schedule</Text>
            <Text style={styles.value}>{data.meetingSchedule}</Text>
          </>
        )}
        {data.meetingLocation && (
          <>
            <Text style={styles.sectionLabel}>Meeting Location</Text>
            <Text style={styles.value}>{data.meetingLocation}</Text>
          </>
        )}
        {data.fundraisingGuidelines && (
          <>
            <Text style={styles.sectionLabel}>Fundraising Guidelines</Text>
            <Text style={styles.value}>{data.fundraisingGuidelines}</Text>
          </>
        )}

        <View style={styles.signatureBlock}>
          <View style={styles.signatureRow}>
            <SignatureLine role="Sponsor Teacher" name={data.sponsorName} signedAt={data.sponsorSignedAt} />
            <SignatureLine role="Administrator" name={data.adminName} signedAt={data.adminSignedAt} />
          </View>
        </View>

        <Text style={styles.footer} fixed>
          Generated by ClubSync on {format(toSchoolZone(data.generatedAt), "MMMM d, yyyy 'at' h:mm a")}. Signatures above are typed names tied to
          each signer&rsquo;s authenticated account and timestamp, not a captured image — this document is the permanent record.
        </Text>
      </Page>
    </Document>
  );
}
